Repository Mixinors/Astromine, pull requests merged in 2020-10, with the labels that each got.

#324 Create de_de.json
  astromine-core/src/main/resources/assets/astromine/lang/de_de.json
Labels: hacktoberfest-accepted, localization

#327 1.11.3
  astromine-foundations/src/main/resources/data/astromine/tags/fluids/normal_breathable.json
  astromine-technologies/src/main/java/com/github/chainmailstudios/astromine/technologies/common/block/AirlockBlock.java
  astromine-technologies/src/main/resources/astromine-technologies.accesswidener
  gradle.properties
Labels: hacktoberfest-accepted, new version

#326 Update zh_cn.json
  astromine-core/src/main/resources/assets/astromine/lang/zh_cn.json
Labels: hacktoberfest-accepted, localization

#335 Update zh_cn.json
  astromine-core/src/main/resources/assets/astromine/lang/zh_cn.json
Labels: hacktoberfest-accepted, localization

#336 fix
  astromine-core/src/main/resources/assets/astromine/lang/zh_cn.json
Labels: hacktoberfest-accepted, localization

#341 Add comparator support
  astromine-core/src/main/java/com/github/chainmailstudios/astromine/common/block/base/BlockWithEntity.java
  astromine-core/src/main/java/com/github/chainmailstudios/astromine/common/block/redstone/ComparatorMode.java
  astromine-core/src/main/java/com/github/chainmailstudios/astromine/common/block/redstone/ComparatorOutput.java
  astromine-technologies/src/main/java/com/github/chainmailstudios/astromine/technologies/common/block/CapacitorBlock.java
  astromine-technologies/src/main/java/com/github/chainmailstudios/astromine/technologies/common/block/FluidExtractorBlock.java
  astromine-technologies/src/main/java/com/github/chainmailstudios/astromine/technologies/common/block/FluidInserterBlock.java
  astromine-technologies/src/main/java/com/github/chainmailstudios/astromine/technologies/common/block/LiquidGeneratorBlock.java
  astromine-technologies/src/main/java/com/github/chainmailstudios/astromine/technologies/common/block/SolidGeneratorBlock.java
  astromine-technologies/src/main/java/com/github/chainmailstudios/astromine/technologies/common/block/TankBlock.java
Labels: hacktoberfest-accepted
